; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_port = COM7
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
built_type = debug

lib_extra_dirs = ~/Documents/Arduino/libraries
lib_deps =
    IRremoteESP8266
    Adafruit GFX Library
    Adafruit SSD1306
    ; ESP32 BLE Keyboard
    https://github.com/JuniorPolegato/ESP32-BLE-Keyboard.git
    NimBLE-Arduino

build_unflags = 
    -std=gnu++11
    -std=c++1

build_flags = 
    -std=gnu++17

[env:esp32-c3-shiftreg]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -std=gnu++17
    -D USE_NIMBLE
    -D USE_SHIFT_REG=1

upload_port = COM9
monitor_port = COM9
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
built_type = debug

lib_extra_dirs = ~/Documents/Arduino/libraries
lib_deps =
    IRremoteESP8266
    Adafruit GFX Library
    Adafruit SSD1306
    ; ESP32 BLE Keyboard
    https://github.com/JuniorPolegato/ESP32-BLE-Keyboard.git#a1df7c8
    ; NimBLE-Arduino
    h2zero/NimBLE-Arduino@2.3.4


build_unflags = 
    -std=gnu++11
    -std=c++1


[env:esp32-c3-singlebtn]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -std=gnu++17
    -D USE_NIMBLE
    -D USE_SHIFT_REG=0

upload_port = COM9
monitor_port = COM9
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
built_type = debug

lib_extra_dirs = ~/Documents/Arduino/libraries
lib_deps =
    IRremoteESP8266
    Adafruit GFX Library
    Adafruit SSD1306
    ; ESP32 BLE Keyboard
    https://github.com/JuniorPolegato/ESP32-BLE-Keyboard.git#a1df7c8
    ; NimBLE-Arduino
    h2zero/NimBLE-Arduino@2.3.4


build_unflags = 
    -std=gnu++11
    -std=c++1